### ISSUE TITLE
Upgrade to libpanel-applet-4-0

### ISSUE THREAD

**Issue by hai-nguyen-van** [jonasfj/gnome-hdaps-applet#1]
Hello,

This applet seems interesting to me. However, it cannot work on my Ubuntu 12.04 due to unresolvable dependencies. Indeed, `libpanel-applet2-0` does **not exist** anymore and now is `libpanel-applet-4-0`. I assume there only needs some small changes to make it work.

This is why, I already tried to do `pkg-config --cflags --libs libpanel-applet-4-0` but this does not work as expected...

**Comment by jonasfj** [comment]
I don't know how to do this in unity, buy for gnome-shell I suspect an extension would be necessary...

Anyways from what I know the old panel extension libraries are obsolete... Anyways this was ever only an indicator applet... It just showed state nothing more...

**Comment by hai-nguyen-van** [comment]
I retried some commands and after executing `gcc $(pkg-config --cflags --libs libpanelapplet-4.0) -o gnome-hdaps-applet gnome-hdaps-applet.c`, I got the following

```
gnome-hdaps-applet.c: In function ‘timer_func’:
gnome-hdaps-applet.c:52:2: error: unknown type name ‘GtkTooltipsData’
gnome-hdaps-applet.c:57:16: error: ‘GtkWidget’ has no member named ‘parent’
gnome-hdaps-applet.c:58:16: warning: assignment makes pointer from integer without a cast [enabled by default]
gnome-hdaps-applet.c:63:38: error: request for member ‘tooltips’ in something not a structure or union
gnome-hdaps-applet.c:67:38: error: request for member ‘tooltips’ in something not a structure or union
gnome-hdaps-applet.c:72:38: error: request for member ‘tooltips’ in something not a structure or union
gnome-hdaps-applet.c: In function ‘gnome_hdaps_applet_fill’:
gnome-hdaps-applet.c:83:2: error: unknown type name ‘GtkTooltips’
gnome-hdaps-applet.c:91:11: warning: assignment makes pointer from integer without a cast [enabled by default]
gnome-hdaps-applet.c: At top level:
gnome-hdaps-applet.c:102:30: error: expected declaration specifiers or ‘...’ before string constant
gnome-hdaps-applet.c:103:30: error: expected declaration specifiers or ‘...’ before ‘(’ token
gnome-hdaps-applet.c:104:30: error: expected declaration specifiers or ‘...’ before string constant
gnome-hdaps-applet.c:105:30: error: expected declaration specifiers or ‘...’ before string constant
gnome-hdaps-applet.c:106:30: error: expected declaration specifiers or ‘...’ before ‘gnome_hdaps_applet_fill’
gnome-hdaps-applet.c:107:30: error: expected declaration specifiers or ‘...’ before ‘(’ token
```

**Comment by jonasfj** [comment]
I don't know what DE you're running... but afaik, gnome-shell uses clutter and unity (whatever version 12.04 is running) is either qt or gtk3 (I can't remember anymore...

Either way, this was written in gtk2, so no chance it'll work either place. You're best bet is to look at the documentation for the DE you're trying to customize a do it from scratch... Should be pretty easy as all this does is check the value of a file and monitor it with inotify.

But do check that HDAPS still uses this file... And do validate that you laptop still has an actual harddrive and not an SSD :)

**Comment by hai-nguyen-van** [comment]
Thanks for the tips. I'll do so :+1:
